### PR TITLE
feat: Show the error message

### PR DESCRIPTION
**Pull request by hiroya-uga**
Hello @shuymn .

**I changed to show the reason why the copy fails.**

I think that it also has some other visual and accessibility problem.
However, it's not something I can fix only my opinion because since they are deeply related to visual design. 

So, I have registered a issue (https://github.com/shuymn/two/issues/271). 
I hope you'll check it out.

p.s.

I usually use your service.
A workmate introduced this Web page to SNS in our company.

Thanks for the great service.

### CODE REVIEW

**Comment by shuymn** [comment]
@hiroya-uga 

Thank you for the contribution.
I'm sorry it took me so long to notice.

I have confirmed that the service is currently unavailable and I will fix it this Saturday and Sunday.

**Comment by shuymn** [comment]
@hiroya-uga 

I just updated the library and the display problem seems to have been resolved.

Could you please check to be sure? 🙇

**Comment by hiroya-uga** [comment]
@shuymn 

The problem had been solved 👀 

> (I'm going to check this PR is separate from the display issue.)

Indeed, this PR doesn't got to do with the issue (#271) ! 🎉

**Comment by hiroya-uga** [comment]
I think this PR will no longer be merged. Sorry I close it.

**Pull request closed without merging**
